/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/home/xetera/topggdocs/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-88bf015c",
    path: "/0-introduction/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-88bf015c").then(next)
    },
  },
  {
    path: "/0-introduction/index.html",
    redirect: "/0-introduction/"
  },
  {
    name: "v-1c8cf742",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c8cf742").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0242b990",
    path: "/tr/0-introduction/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0242b990").then(next)
    },
  },
  {
    path: "/tr/0-introduction/index.html",
    redirect: "/tr/0-introduction/"
  },
  {
    name: "v-0fa611f2",
    path: "/tr/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fa611f2").then(next)
    },
  },
  {
    path: "/tr/index.html",
    redirect: "/tr/"
  },
  {
    name: "v-c560869c",
    path: "/zh/0-getting-started/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c560869c").then(next)
    },
  },
  {
    path: "/zh/0-getting-started/index.html",
    redirect: "/zh/0-getting-started/"
  },
  {
    name: "v-1e37d5a8",
    path: "/zh/1-configurations/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e37d5a8").then(next)
    },
  },
  {
    path: "/zh/1-configurations/index.html",
    redirect: "/zh/1-configurations/"
  },
  {
    name: "v-edeff422",
    path: "/zh/1-configurations/components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edeff422").then(next)
    },
  },
  {
    name: "v-17868767",
    path: "/zh/1-configurations/template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17868767").then(next)
    },
  },
  {
    name: "v-5301981c",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5301981c").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]