/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello, World.",
  "description": "📦 🎨 A api-friendly theme for VuePress.",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Getting Started",
      "frontmatter": {},
      "regularPath": "/0-introduction/",
      "relativePath": "0-introduction/README.md",
      "key": "v-88bf015c",
      "path": "/0-introduction/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "title": "Hello, World.",
        "description": "Not sure where to start? We’ve put together some handy guides and reference documentation you can use to start building.",
        "actionText": "Getting Started",
        "actionLink": "/0-introduction/",
        "footer": "Open Source on [GitHub](https://github.com/sqrthree/vuepress-theme-api), Made by [@sqrthree](https://github.com/sqrthree), Power by [vuepress](https://github.com/vuejs/vuepress)."
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1c8cf742",
      "path": "/",
      "headers": [
        {
          "level": 3,
          "title": "As Easy as 1, 2, 3",
          "slug": "as-easy-as-1-2-3"
        },
        {
          "level": 2,
          "title": "Build for RESTful API",
          "slug": "build-for-restful-api"
        }
      ],
      "lastUpdated": "4/25/2020, 5:26:09 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/tr/0-introduction/",
      "relativePath": "tr/0-introduction/README.md",
      "key": "v-0242b990",
      "path": "/tr/0-introduction/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "title": "Hello world",
        "description": "Description link",
        "actionText": "Get started",
        "actionLink": "/tr/0-introduction",
        "footer": "Open Source on [GitHub](https://github.com/sqrthree/vuepress-theme-api), Made by [@sqrthree](https://github.com/sqrthree), Power by [vuepress](https://github.com/vuejs/vuepress)."
      },
      "regularPath": "/tr/",
      "relativePath": "tr/README.md",
      "key": "v-0fa611f2",
      "path": "/tr/"
    },
    {
      "title": "起步",
      "frontmatter": {},
      "regularPath": "/zh/0-getting-started/",
      "relativePath": "zh/0-getting-started/README.md",
      "key": "v-c560869c",
      "path": "/zh/0-getting-started/",
      "headers": [
        {
          "level": 2,
          "title": "构建于",
          "slug": "构建于"
        },
        {
          "level": 2,
          "title": "环境依赖",
          "slug": "环境依赖"
        },
        {
          "level": 2,
          "title": "应用主题",
          "slug": "应用主题"
        }
      ],
      "lastUpdated": "4/25/2020, 5:26:09 PM"
    },
    {
      "title": "基本配置",
      "frontmatter": {
        "title": "基本配置"
      },
      "regularPath": "/zh/1-configurations/",
      "relativePath": "zh/1-configurations/README.md",
      "key": "v-1e37d5a8",
      "path": "/zh/1-configurations/",
      "headers": [
        {
          "level": 2,
          "title": "配置文件",
          "slug": "配置文件"
        },
        {
          "level": 3,
          "title": "VuePress 配置",
          "slug": "vuepress-配置"
        },
        {
          "level": 2,
          "title": "首页配置",
          "slug": "首页配置"
        },
        {
          "level": 2,
          "title": "侧边导航配置",
          "slug": "侧边导航配置"
        },
        {
          "level": 3,
          "title": "自定义侧边栏顺序",
          "slug": "自定义侧边栏顺序"
        },
        {
          "level": 3,
          "title": "自定义侧边栏内容",
          "slug": "自定义侧边栏内容"
        },
        {
          "level": 3,
          "title": "自定义侧边栏顺序：",
          "slug": "自定义侧边栏顺序："
        },
        {
          "level": 3,
          "title": "自定义侧边栏内容：",
          "slug": "自定义侧边栏内容："
        },
        {
          "level": 2,
          "title": "页面布局",
          "slug": "页面布局"
        },
        {
          "level": 2,
          "title": "多语言配置",
          "slug": "多语言配置"
        }
      ],
      "lastUpdated": "4/25/2020, 5:26:09 PM"
    },
    {
      "title": "内置组件",
      "frontmatter": {
        "title": "内置组件"
      },
      "regularPath": "/zh/1-configurations/components.html",
      "relativePath": "zh/1-configurations/components.md",
      "key": "v-edeff422",
      "path": "/zh/1-configurations/components.html",
      "headers": [
        {
          "level": 2,
          "title": "Block 组件",
          "slug": "block-组件"
        },
        {
          "level": 2,
          "title": "Example 组件",
          "slug": "example-组件"
        },
        {
          "level": 2,
          "title": "CURL 组件",
          "slug": "curl-组件"
        },
        {
          "level": 2,
          "title": "Button 组件",
          "slug": "button-组件"
        },
        {
          "level": 2,
          "title": "Section 组件",
          "slug": "section-组件"
        }
      ],
      "lastUpdated": "4/25/2020, 5:26:09 PM"
    },
    {
      "title": "文件模板",
      "frontmatter": {
        "title": "文件模板"
      },
      "regularPath": "/zh/1-configurations/template.html",
      "relativePath": "zh/1-configurations/template.md",
      "key": "v-17868767",
      "path": "/zh/1-configurations/template.html",
      "lastUpdated": "4/25/2020, 5:26:09 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "title": "Hello, World.",
        "description": "不知道从哪里开始？我们准备了一些你可以用来开始构建的便捷指南和参考文档。",
        "actionText": "开始出发",
        "actionLink": "/zh/0-getting-started/",
        "footer": "Open Source on [GitHub](https://github.com/sqrthree/vuepress-theme-api), Made by [@sqrthree](https://github.com/sqrthree), Power by [vuepress](https://github.com/vuejs/vuepress)."
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-5301981c",
      "path": "/zh/",
      "headers": [
        {
          "level": 2,
          "title": "1、2、3 很简单",
          "slug": "_1、2、3-很简单"
        },
        {
          "level": 2,
          "title": "为 RESTful API 而生",
          "slug": "为-restful-api-而生"
        }
      ],
      "lastUpdated": "4/25/2020, 5:26:09 PM"
    }
  ],
  "themeConfig": {
    "locales": {
      "/": {
        "selectText": "Languages",
        "label": "English"
      },
      "/tr/": {
        "selectText": "Diller",
        "label": "Turkce"
      },
      "/zh/": {
        "selectText": "选择语言",
        "label": "简体中文"
      }
    },
    "repo": "top-gg/docs",
    "repoLabel": "Contribute!",
    "docsRepo": "top-gg/docs",
    "docsDir": "docs",
    "docsBranch": "master",
    "editLinks": true,
    "lastUpdated": true
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "Top.gg Docs",
      "text": "english",
      "description": "Documentation for top.gg public API",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-hans",
      "title": "Hello, World.",
      "text": "中文",
      "description": "📦 🎨 一个面向 RESTful API 设计的开箱即用主题。",
      "path": "/zh/"
    },
    "/tr/": {
      "lang": "tr-TR",
      "title": "Top.gg memes",
      "text": "Turkce",
      "description": "dabby",
      "path": "/tr/"
    }
  }
}